<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\BasesBackend.Domain\BasesBackend.Domain.csproj" />
    <ProjectReference Include="..\BasesBackend.Dto\BasesBackend.Dto.csproj" />
    <ProjectReference Include="..\BasesBackend.Infrastructure\BasesBackend.Infrastructure.csproj" />
    <ProjectReference Include="..\BasesBackend.Exceptions\BasesBackend.Exceptions.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>