CREATE DATABASE ProyectoBD2;
USE ProyectoBD2;

CREATE TABLE CLIENTE (
    IdCliente INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Telefono VARCHAR(20),
    Correo VARCHAR(100),
    Direccion VARCHAR(200),
    RolCliente ENUM('ORIGEN','DESTINO','AMBOS') NOT NULL
);

CREATE TABLE PRODUCTO (
    IdProducto INT AUTO_INCREMENT PRIMARY KEY,
    Codigo VARCHAR(20) UNIQUE NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Detalle VARCHAR(255),
    CantidadActual INT NOT NULL DEFAULT 0,
    StockCritico INT NOT NULL,
    Bodega VARCHAR(50) NOT NULL,
    Pasillo VARCHAR(50) NOT NULL,
    Estante VARCHAR(50) NOT NULL
);

CREATE TABLE RECEPCION (
    IdRecepcion INT AUTO_INCREMENT PRIMARY KEY,
    IdCliente INT NOT NULL,
    NumeroLote VARCHAR(50) NOT NULL,
    FechaRecepcion DATETIME NOT NULL,
    UsuarioAtendio VARCHAR(50) NOT NULL,

    CONSTRAINT FK_RECEPCION_CLIENTE
    FOREIGN KEY (IdCliente)
    REFERENCES CLIENTE(IdCliente)
);

CREATE TABLE DETALLE_RECEPCION (
    IdDetalleRecepcion INT AUTO_INCREMENT PRIMARY KEY,
    IdRecepcion INT NOT NULL,
    IdProducto INT NOT NULL,
    Cantidad INT NOT NULL,

    CONSTRAINT FK_DETALLE_RECEPCION
    FOREIGN KEY (IdRecepcion)
    REFERENCES RECEPCION(IdRecepcion),

    CONSTRAINT FK_DETALLE_RECEPCION_PRODUCTO
    FOREIGN KEY (IdProducto)
    REFERENCES PRODUCTO(IdProducto)
);

CREATE TABLE DESPACHO (
    IdDespacho INT AUTO_INCREMENT PRIMARY KEY,
    IdCliente INT NOT NULL,
    FechaDespacho DATETIME NOT NULL,
    Estado ENUM('PENDIENTE','PROCESADO','CANCELADO') NOT NULL,
    Operario VARCHAR(50) NOT NULL,

    CONSTRAINT FK_DESPACHO_CLIENTE
    FOREIGN KEY (IdCliente)
    REFERENCES CLIENTE(IdCliente)
);

CREATE TABLE CARRITO_DESPACHO (
    IdCarrito INT AUTO_INCREMENT PRIMARY KEY,
    IdDespacho INT NOT NULL,
    IdProducto INT NOT NULL,
    Cantidad INT NOT NULL,

    CONSTRAINT FK_CARRITO_DESPACHO
    FOREIGN KEY (IdDespacho)
    REFERENCES DESPACHO(IdDespacho),

    CONSTRAINT FK_CARRITO_PRODUCTO
    FOREIGN KEY (IdProducto)
    REFERENCES PRODUCTO(IdProducto)
);

CREATE TABLE DETALLE_DESPACHO (
    IdDetalle INT AUTO_INCREMENT PRIMARY KEY,
    IdDespacho INT NOT NULL,
    IdProducto INT NOT NULL,
    Cantidad INT NOT NULL,

    CONSTRAINT FK_DETALLE_DESPACHO
    FOREIGN KEY (IdDespacho)
    REFERENCES DESPACHO(IdDespacho),

    CONSTRAINT FK_DETALLE_PRODUCTO
    FOREIGN KEY (IdProducto)
    REFERENCES PRODUCTO(IdProducto)
);

CREATE TABLE AUDITORIA_PRODUCTO (
    IdAuditoria INT AUTO_INCREMENT PRIMARY KEY,
    IdProducto INT NOT NULL,
    FechaMovimiento DATETIME NOT NULL,
    CantidadAnterior INT NOT NULL,
    CantidadNueva INT NOT NULL,
    UsuarioModificacion VARCHAR(50) NOT NULL,

    CONSTRAINT FK_AUDITORIA_PRODUCTO
    FOREIGN KEY (IdProducto)
    REFERENCES PRODUCTO(IdProducto)
);